### ISSUE TITLE
catch no email and password when connected...

### ISSUE THREAD

**Issue by Axxl07** [FlippieHacks/EvilPortalGenerator#1]
Hi,
I've easily made some portals with your generator, works great and I obtain good looking portals.

I can also  easily connect to my portals with my smartphone and I can see the server is well running on my flipper zero...when I connect to my fake portals I can't get any emails or passwords received by Flipper.
With the portals you can find with evil portal App it works well ...I receive all infos.
Weeks I'm looking to find the bug but found nothing so that's why I ask... ;-)
If you see something that can help me ...
Best regards, 
Alex.

**Comment by FlippieHacks** [comment]
Hi man,
Sorry I haven't been around here a lot last week
I see that you found a fix for this in the other thread? 
I'll have a look at it myself in the next days as well :)
Thanks for letting me know and enjoy the script!

**Comment by Axxl07** [comment]
Hi FlipieHacks, no worries ;-)
Yes, found a personnal solution, tikering html code from Portal provided with EvilPortalMain...
Let me know if you fix the problem from your generator...and thanks a lot for this script !!
